### ISSUE TITLE
获取群成员列表失败

### ISSUE THREAD

**Issue by kKsk03** [LSTM-Kirigaya/Lagrange.onebot#1]
## 问题：获取群成员列表失败
今天寻思写个获取群成员列表和数据库已记录群成员每日自动比对并汇报的功能  
测试的时候发现了问题（也许是问题？又或者是我写的有问题？不太清楚捏）  

## 代码
```typescript
@mapper.onGroup(246142027)
async handleGroup_AdminGroup(c: LagrangeContext<GroupMessage>) {
    const allGroupMemberInfo = await c.getGroupMemberList(181748185);
    console.log(allGroupMemberInfo);
    c.finishSession()
}
```

## 输出
```console
null
```
> 实际上 `181748185` 这个群有180个人，然而始终返回都是 `null`。按照onebot的文档，这里正常应该返回 `json` 数据才对

**Comment by LSTM-Kirigaya** [comment]
我发现错误了，我的 send 系列函数都没有对 ws 的回传信息做处理，我现在正在修复，今晚发一版新的。
